### ISSUE TITLE
Code blocks do not wrap lines, such as shell blocks.(```shell code ```)

### ISSUE THREAD

**Issue by itldr** [ostera/tldr.jsx#171]
Code blocks do not wrap lines, such as shell blocks.(```shell code ```)
![image](https://user-images.githubusercontent.com/76577309/109092083-e780d080-7750-11eb-949c-e1f432ca8e13.png)

**Comment by bl-ue** [comment]
@itldr it seems to me that this is intentional.  That's what GitHub itself does, e.g.:

<img width="626" alt="Screen Shot 2021-02-24 at 9 15 19 PM" src="https://user-images.githubusercontent.com/54780737/109092977-8bcd2d80-76e5-11eb-9818-0a9be8e77d47.png">

The code block (denoted by three tildes: \`\`\`...\`\`\`) is a separate entity, and not supposed to have word wrap, whereas the inline code (denoted by one tilde: \`...\`) is just a normal sentence except it's styled as code, and therefore it should be wrapped as normal sentences are.

**Comment by bl-ue** [comment]
Note:

Inline, three tildes (\`\`\`) has the same effect as a single tilde (\`).  e.g: this is made by three tildes: ```code```, this is made by one tilde: `code`.

When opening \`\`\` is on one line and the closing \`\`\` is on another, it becomes a code block:

```
code
```

Not so, though, for the single tilde:

`
code
`

**Comment by itldr** [comment]
> Note:
> 
> Inline, three tildes (```) has the same effect as a single tilde (`). e.g: this is made by three tildes: `code`, this is made by one tilde: `code`.
> 
> When opening ``` is on one line and the closing ``` is on another, it becomes a code block:
> 
> ```
> code
> ```
> 
> Not so, though, for the single tilde:
> 
> `code`

What you said is very reasonable. Thank you.However, if each line of code in the block is too long, it will feel incongruous to display it on the page.

**Comment by bl-ue** [comment]
Then, I think you should always use single tildes (\`) for these pages.  That should make word wrap always happen.

**Comment by itldr** [comment]
> Then, I think you should always use single tildes (`) for these pages. That should make word wrap always happen.

Yes, I should use (`) more than  (\```) .For me   (\```) is a convenient way to write it, maybe I'm lazy, haha.You always know so much, and I will continue to learn from you.thank you！
