### ISSUE TITLE
Serve over HTTPS

### ISSUE THREAD

**Issue by waldyrious** [ostera/tldr.jsx#43]
Github now makes this easy with a simple configuration toggle (IIUC): https://github.com/blog/2186-https-for-github-pages

This is required for proper embedding on tldr-pages.github.io

**Comment by ostera** [comment]
Good point! Need to figure out the HTML5 PushState routing around that. AFAIK, can't be done from Github Pages, that's why I have the site hosted on Amazon S3. I might be able to get a * certificate for my domain.

The other option would be to go all in, and host the whole thing (client and landing page) as one on Github.

**Comment by ostera** [comment]
In the meantime, https://github.com/tldr-pages/tldr-pages.github.io/commit/260a8ba04a6c1314e69f2206137e8188f16b7d09 fixes the iframe src.

**Comment by waldyrious** [comment]
Ok, although the iframe still doesn't work if the tldr website is loaded over https (in Chome at least). Anyway, sorry for [jumping the gun](https://github.com/tldr-pages/tldr-pages.github.io/commit/9fe2149), I forgot about the extra stuff you do under the hood 😇

**Comment by waldyrious** [comment]
Have you looked at Let's Encrypt certificates?

**Comment by ostera** [comment]
Done :) https://tldr.ostera.io/

**Comment by ostera** [comment]
@waldyrious ah, forgot to add one error redirect (403s -> index) :P to make the permalink work. CloudFront is redeploying the distribution now, should take a few minutes.

**Comment by waldyrious** [comment]
Good catch. It appears to be working now :)
